In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import re
import pandas as pd

In [ ]:
BASE_PATH = "/content/drive/MyDrive/AI-Placement-Copilot-ML"

job_path = os.path.join(BASE_PATH, "datasets/job_descriptions/postings.csv")
processed_path = os.path.join(BASE_PATH, "processed")

In [ ]:
df_jobs = pd.read_csv(job_path)

print("Total Jobs:", len(df_jobs))
df_jobs.head()

Total Jobs: 9380

,job_title,company,job_location,job_link,first_seen,search_city,search_country,job level,job_type,job_summary,job_skills
0,C# Software Engineer,E Tech Group,"West Chester, OH",https://www.linkedin.com/jobs/view/c%23-softwa...,2023-12-25,Covington,United States,Associate,Remote,"At E Tech Group, joining our team means joinin...","C#, .NET, WPF, ASP.NET MVC, WebAPI, C++, Progr..."
1,Software Implementation Engineer,Kardex,"Cincinnati, OH",https://www.linkedin.com/jobs/view/software-im...,2023-12-25,Covington,United States,Associate,Remote,Kardex Remstar is looking for a\nSoftware Impl...,"Software Implementation, Software Testing, Sof..."
2,"Senior Software Engineer, Back End (Go, AWS, J...",Jobs for Humanity,"Chattanooga, TN",https://www.linkedin.com/jobs/view/senior-soft...,2023-12-25,Chattanooga,United States,Mid senior,Onsite,Company Description\nJobs for Humanity is part...,"Java, Python, SQL, Node.js, Go, Scala, AWS, GC..."
3,"Senior Manager, Software Engineering, Full Stack",Jobs for Humanity,"Chattanooga, TN",https://www.linkedin.com/jobs/view/senior-mana...,2023-12-25,Chattanooga,United States,Mid senior,Onsite,Company Description\nJobs for Humanity is part...,"JavaScript, Java, TypeScript, SQL, Python, Go,..."
4,"Lead Software Engineer, Full Stack(JavaScript/...",Jobs for Humanity,"Chattanooga, TN",https://www.linkedin.com/jobs/view/lead-softwa...,2023-12-25,Chattanooga,United States,Mid senior,Onsite,Company Description\nJobs for Humanity is part...,"JavaScript, Java, AWS, Vue.js, HTML/CSS, TypeS..."

In [ ]:
df_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9380 entries, 0 to 9379
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_title       9380 non-null   object
 1   company         9380 non-null   object
 2   job_location    9380 non-null   object
 3   job_link        9380 non-null   object
 4   first_seen      9380 non-null   object
 5   search_city     9380 non-null   object
 6   search_country  9380 non-null   object
 7   job level       9380 non-null   object
 8   job_type        9380 non-null   object
 9   job_summary     9376 non-null   object
 10  job_skills      9367 non-null   object
dtypes: object(11)
memory usage: 806.2+ KB

In [ ]:
df_jobs = df_jobs[
    [
        "job_title",
        "company",
        "job_location",
        "job_link",
        "first_seen",
        "search_city",
        "search_country",
        "job level",
        "job_type",
        "job_summary",
        "job_skills"
    ]
]

df_jobs.head()

,job_title,company,job_location,job_link,first_seen,search_city,search_country,job level,job_type,job_summary,job_skills
0,C# Software Engineer,E Tech Group,"West Chester, OH",https://www.linkedin.com/jobs/view/c%23-softwa...,2023-12-25,Covington,United States,Associate,Remote,"At E Tech Group, joining our team means joinin...","C#, .NET, WPF, ASP.NET MVC, WebAPI, C++, Progr..."
1,Software Implementation Engineer,Kardex,"Cincinnati, OH",https://www.linkedin.com/jobs/view/software-im...,2023-12-25,Covington,United States,Associate,Remote,Kardex Remstar is looking for a\nSoftware Impl...,"Software Implementation, Software Testing, Sof..."
2,"Senior Software Engineer, Back End (Go, AWS, J...",Jobs for Humanity,"Chattanooga, TN",https://www.linkedin.com/jobs/view/senior-soft...,2023-12-25,Chattanooga,United States,Mid senior,Onsite,Company Description\nJobs for Humanity is part...,"Java, Python, SQL, Node.js, Go, Scala, AWS, GC..."
3,"Senior Manager, Software Engineering, Full Stack",Jobs for Humanity,"Chattanooga, TN",https://www.linkedin.com/jobs/view/senior-mana...,2023-12-25,Chattanooga,United States,Mid senior,Onsite,Company Description\nJobs for Humanity is part...,"JavaScript, Java, TypeScript, SQL, Python, Go,..."
4,"Lead Software Engineer, Full Stack(JavaScript/...",Jobs for Humanity,"Chattanooga, TN",https://www.linkedin.com/jobs/view/lead-softwa...,2023-12-25,Chattanooga,United States,Mid senior,Onsite,Company Description\nJobs for Humanity is part...,"JavaScript, Java, AWS, Vue.js, HTML/CSS, TypeS..."

In [ ]:
df_jobs.isnull().sum()

job_title          0
company            0
job_location       0
job_link           0
first_seen         0
search_city        0
search_country     0
job level          0
job_type           0
job_summary        4
job_skills        13
dtype: int64

In [ ]:
df_jobs["job_summary"] = df_jobs["job_summary"].fillna("")
df_jobs["job_skills"] = df_jobs["job_skills"].fillna("")

In [ ]:
def clean_text(text):
    text = str(text)

    text = re.sub(r"\n+", " ", text)
    text = re.sub(r"\t+", " ", text)
    text = re.sub(r" +", " ", text)
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"www\S+", "", text)

    return text.strip()

In [ ]:
df_jobs["job_summary"] = df_jobs["job_summary"].apply(clean_text)
df_jobs["job_skills"] = df_jobs["job_skills"].apply(clean_text)

df_jobs.head()

,job_title,company,job_location,job_link,first_seen,search_city,search_country,job level,job_type,job_summary,job_skills
0,C# Software Engineer,E Tech Group,"West Chester, OH",https://www.linkedin.com/jobs/view/c%23-softwa...,2023-12-25,Covington,United States,Associate,Remote,"At E Tech Group, joining our team means joinin...","C#, .NET, WPF, ASP.NET MVC, WebAPI, C++, Progr..."
1,Software Implementation Engineer,Kardex,"Cincinnati, OH",https://www.linkedin.com/jobs/view/software-im...,2023-12-25,Covington,United States,Associate,Remote,Kardex Remstar is looking for a Software Imple...,"Software Implementation, Software Testing, Sof..."
2,"Senior Software Engineer, Back End (Go, AWS, J...",Jobs for Humanity,"Chattanooga, TN",https://www.linkedin.com/jobs/view/senior-soft...,2023-12-25,Chattanooga,United States,Mid senior,Onsite,Company Description Jobs for Humanity is partn...,"Java, Python, SQL, Node.js, Go, Scala, AWS, GC..."
3,"Senior Manager, Software Engineering, Full Stack",Jobs for Humanity,"Chattanooga, TN",https://www.linkedin.com/jobs/view/senior-mana...,2023-12-25,Chattanooga,United States,Mid senior,Onsite,Company Description Jobs for Humanity is partn...,"JavaScript, Java, TypeScript, SQL, Python, Go,..."
4,"Lead Software Engineer, Full Stack(JavaScript/...",Jobs for Humanity,"Chattanooga, TN",https://www.linkedin.com/jobs/view/lead-softwa...,2023-12-25,Chattanooga,United States,Mid senior,Onsite,Company Description Jobs for Humanity is partn...,"JavaScript, Java, AWS, Vue.js, HTML/CSS, TypeS..."

In [ ]:
df_jobs.info()
df_jobs.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9380 entries, 0 to 9379
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_title       9380 non-null   object
 1   company         9380 non-null   object
 2   job_location    9380 non-null   object
 3   job_link        9380 non-null   object
 4   first_seen      9380 non-null   object
 5   search_city     9380 non-null   object
 6   search_country  9380 non-null   object
 7   job level       9380 non-null   object
 8   job_type        9380 non-null   object
 9   job_summary     9380 non-null   object
 10  job_skills      9380 non-null   object
dtypes: object(11)
memory usage: 806.2+ KB

,job_title,company,job_location,job_link,first_seen,search_city,search_country,job level,job_type,job_summary,job_skills
0,C# Software Engineer,E Tech Group,"West Chester, OH",https://www.linkedin.com/jobs/view/c%23-softwa...,2023-12-25,Covington,United States,Associate,Remote,"At E Tech Group, joining our team means joinin...","C#, .NET, WPF, ASP.NET MVC, WebAPI, C++, Progr..."
1,Software Implementation Engineer,Kardex,"Cincinnati, OH",https://www.linkedin.com/jobs/view/software-im...,2023-12-25,Covington,United States,Associate,Remote,Kardex Remstar is looking for a Software Imple...,"Software Implementation, Software Testing, Sof..."
2,"Senior Software Engineer, Back End (Go, AWS, J...",Jobs for Humanity,"Chattanooga, TN",https://www.linkedin.com/jobs/view/senior-soft...,2023-12-25,Chattanooga,United States,Mid senior,Onsite,Company Description Jobs for Humanity is partn...,"Java, Python, SQL, Node.js, Go, Scala, AWS, GC..."
3,"Senior Manager, Software Engineering, Full Stack",Jobs for Humanity,"Chattanooga, TN",https://www.linkedin.com/jobs/view/senior-mana...,2023-12-25,Chattanooga,United States,Mid senior,Onsite,Company Description Jobs for Humanity is partn...,"JavaScript, Java, TypeScript, SQL, Python, Go,..."
4,"Lead Software Engineer, Full Stack(JavaScript/...",Jobs for Humanity,"Chattanooga, TN",https://www.linkedin.com/jobs/view/lead-softwa...,2023-12-25,Chattanooga,United States,Mid senior,Onsite,Company Description Jobs for Humanity is partn...,"JavaScript, Java, AWS, Vue.js, HTML/CSS, TypeS..."

In [ ]:
save_path = os.path.join(processed_path, "clean_jobs.csv")

df_jobs.to_csv(save_path, index=False)

print("Clean job dataset saved successfully!")

Clean job dataset saved successfully!