In [ ]:
!pip install -q pandas openpyxl

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import glob
import pandas as pd

In [ ]:
BASE = "/content/drive/MyDrive/AI-Placement-Copilot-ML/datasets/processed"

company_root = os.path.join(
    BASE,
    "leetcode-company-wise-interview-questions-main",
    "leetcode-company-wise-interview-questions-main"
)

In [ ]:
company_folders = [
    folder
    for folder in os.listdir(company_root)
    if os.path.isdir(os.path.join(company_root, folder))
]

print("Companies:", len(company_folders))
print(company_folders[:10])

Companies: 660
['1kosmos', '6sense', 'accelya', 'accenture', 'accolite', 'acko', 'acorns', 'activision', 'adobe', 'adp']

In [ ]:
dfs = []

for company in company_folders:

    csv_path = os.path.join(
        company_root,
        company,
        "all.csv"
    )

    if os.path.exists(csv_path):

        df = pd.read_csv(csv_path)

        df["company"] = company

        dfs.append(df)

print("Loaded:", len(dfs))

Loaded: 654

In [ ]:
company_df = pd.concat(dfs, ignore_index=True)

print(company_df.shape)

company_df.head()

(17641, 11)

,ID,URL,Title,Difficulty,Acceptance %,Frequency %,Topic Tags,Pattern,Revision Priority,Notes,company
0,2938,https://leetcode.com/problems/separate-black-a...,Separate Black and White Balls,Medium,63.9%,100.0%,Core DSA,Implementation / Reasoning,High,Must revise; common company/OA pattern.,1kosmos
1,2571,https://leetcode.com/problems/minimum-operatio...,Minimum Operations to Reduce an Integer to 0,Medium,62.4%,100.0%,Arrays,Sorting / Prefix / Scan,High,Must revise; common company/OA pattern.,6sense
2,1105,https://leetcode.com/problems/filling-bookcase...,Filling Bookcase Shelves,Medium,68.6%,87.5%,Core DSA,Implementation / Reasoning,High,Must revise; common company/OA pattern.,6sense
3,1894,https://leetcode.com/problems/find-the-student...,Find the Student that Will Replace the Chalk,Medium,53.2%,87.5%,Core DSA,Implementation / Reasoning,High,Must revise; common company/OA pattern.,6sense
4,1497,https://leetcode.com/problems/check-if-array-p...,Check If Array Pairs Are Divisible by k,Medium,46.2%,87.5%,Arrays,Sorting / Prefix / Scan,High,Must revise; common company/OA pattern.,6sense

In [ ]:
company_df.columns = [
    col.strip().lower().replace(" ", "_")
    for col in company_df.columns
]

company_df.drop_duplicates(inplace=True)

company_df.reset_index(drop=True, inplace=True)

In [ ]:
company_df.to_csv(
    "/content/drive/MyDrive/AI-Placement-Copilot-ML/datasets/processed/company_questions.csv",
    index=False
)

print("Company dataset saved!")

Company dataset saved!

In [ ]:
hr = pd.read_csv(
"/content/drive/MyDrive/AI-Placement-Copilot-ML/datasets/processed/archive (4)/full_interview_questions_dataset.csv"
)

hr.head()

,question,role,category,difficulty
0,Explain the difference between list and tuple.,Software Engineer,Technical,medium
1,Explain the difference between list and array.,Software Engineer,Technical,medium
2,Explain the difference between list and hashmap.,Software Engineer,Technical,medium
3,Explain the difference between list and recurs...,Software Engineer,Technical,easy
4,Explain the difference between list and inheri...,Software Engineer,Technical,hard

In [ ]:
hr.columns = [
    c.lower().strip().replace(" ","_")
    for c in hr.columns
]

hr.drop_duplicates(inplace=True)

hr.to_csv(
"/content/drive/MyDrive/AI-Placement-Copilot-ML/datasets/processed/hr_questions.csv",
index=False
)

In [ ]:
import pandas as pd

company = pd.read_csv(
    "/content/drive/MyDrive/AI-Placement-Copilot-ML/datasets/processed/company_questions.csv"
)

print(company.shape)
company.head()

(17641, 11)

,id,url,title,difficulty,acceptance_%,frequency_%,topic_tags,pattern,revision_priority,notes,company
0,2938,https://leetcode.com/problems/separate-black-a...,Separate Black and White Balls,Medium,63.9%,100.0%,Core DSA,Implementation / Reasoning,High,Must revise; common company/OA pattern.,1kosmos
1,2571,https://leetcode.com/problems/minimum-operatio...,Minimum Operations to Reduce an Integer to 0,Medium,62.4%,100.0%,Arrays,Sorting / Prefix / Scan,High,Must revise; common company/OA pattern.,6sense
2,1105,https://leetcode.com/problems/filling-bookcase...,Filling Bookcase Shelves,Medium,68.6%,87.5%,Core DSA,Implementation / Reasoning,High,Must revise; common company/OA pattern.,6sense
3,1894,https://leetcode.com/problems/find-the-student...,Find the Student that Will Replace the Chalk,Medium,53.2%,87.5%,Core DSA,Implementation / Reasoning,High,Must revise; common company/OA pattern.,6sense
4,1497,https://leetcode.com/problems/check-if-array-p...,Check If Array Pairs Are Divisible by k,Medium,46.2%,87.5%,Arrays,Sorting / Prefix / Scan,High,Must revise; common company/OA pattern.,6sense

In [ ]:
print(company.columns.tolist())

['id', 'url', 'title', 'difficulty', 'acceptance_%', 'frequency_%', 'topic_tags', 'pattern', 'revision_priority', 'notes', 'company']

In [ ]:
company.columns = [
    c.lower().strip().replace(" ", "_")
    for c in company.columns
]

company.drop_duplicates(inplace=True)

company.fillna("", inplace=True)

company.reset_index(drop=True, inplace=True)

In [ ]:
company.isnull().sum()

id                   0
url                  0
title                0
difficulty           0
acceptance_%         0
frequency_%          0
topic_tags           0
pattern              0
revision_priority    0
notes                0
company              0
dtype: int64

In [ ]:
company.to_csv(
    "/content/drive/MyDrive/AI-Placement-Copilot-ML/datasets/processed/company_questions_clean.csv",
    index=False
)

print("Company dataset cleaned successfully!")

Company dataset cleaned successfully!

In [ ]:
hr = pd.read_csv(
    "/content/drive/MyDrive/AI-Placement-Copilot-ML/datasets/processed/hr_questions.csv"
)

company = pd.read_csv(
    "/content/drive/MyDrive/AI-Placement-Copilot-ML/datasets/processed/company_questions_clean.csv"
)

print("Company Questions:", len(company))
print("HR Questions:", len(hr))

Company Questions: 17641
HR Questions: 660

In [ ]:
print(company_df.columns.tolist())
print(company_df.head())

['id', 'url', 'title', 'difficulty', 'acceptance_%', 'frequency_%', 'topic_tags', 'pattern', 'revision_priority', 'notes', 'company']
     id                                                url  \
0  2938  https://leetcode.com/problems/separate-black-a...
1  2571  https://leetcode.com/problems/minimum-operatio...
2  1105  https://leetcode.com/problems/filling-bookcase...
3  1894  https://leetcode.com/problems/find-the-student...
4  1497  https://leetcode.com/problems/check-if-array-p...

                                          title difficulty acceptance_%  \
0                Separate Black and White Balls     Medium        63.9%
1  Minimum Operations to Reduce an Integer to 0     Medium        62.4%
2                      Filling Bookcase Shelves     Medium        68.6%
3  Find the Student that Will Replace the Chalk     Medium        53.2%
4       Check If Array Pairs Are Divisible by k     Medium        46.2%

  frequency_% topic_tags                     pattern revision_priority  \
0      100.0%   Core DSA  Implementation / Reasoning              High
1      100.0%     Arrays     Sorting / Prefix / Scan              High
2       87.5%   Core DSA  Implementation / Reasoning              High
3       87.5%   Core DSA  Implementation / Reasoning              High
4       87.5%     Arrays     Sorting / Prefix / Scan              High

                                     notes  company
0  Must revise; common company/OA pattern.  1kosmos
1  Must revise; common company/OA pattern.   6sense
2  Must revise; common company/OA pattern.   6sense
3  Must revise; common company/OA pattern.   6sense
4  Must revise; common company/OA pattern.   6sense